[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./out" },
    { access = "write", path = "./reports" }
]
solc = "0.8.25"
ffi = true
evm_version = "cancun"
remappings = [
    'xchain-helpers/=lib/xchain-helpers/src/',
    'forge-std/=lib/forge-std/src/',
]
no_match_path = "src/examples/*"

[lint]
exclude_lints = ["asm-keccak256", "mixed-case-variable", "mixed-case-function"]

[etherscan]
mainnet = { key = "${MAINNET_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"